services:
  backend:
    build:
      dockerfile: Dockerfile
      tags:
        - blogi.felixi.org:5000/muuvit-backend
    ports:
      - "3000:3000"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
